### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by edgarscr** [Ramotion/showroom#34]
This library you dont have in android studio version?

**Comment by Juriv** [comment]
https://github.com/Ramotion/showroom-android

**Comment by edgarscr** [comment]
@Juriv hi i dont need the card slider i need the navegation menu 

![image](https://user-images.githubusercontent.com/33737821/66854030-2dffd180-ef46-11e9-8ccb-dd28d87e7d56.png)

i searched entire project and they dont have the navegation bar

**Comment by Juriv** [comment]
@edgarscr yes you are right, we don't have this lib for android. I don't think we will be able to implement it in near future because all of our android developers are working on long-term project
